rust_library(
    name = "common",
    srcs = glob(["src/**/*,rs"]),
    deps = [
        "//third-party:anyhow",
        "//third-party:sea-orm",
        "//third-party:thiserror",
        "//third-party:clap",
        "//third-party:idgenerator",
        "//third-party:serde",
        "//third-party:config",
        "//third-party:envsubst",
    ],
    crate_root = "src/lib.rs"
)
