rust_library(
    name = "atlas",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "//third-party:async-openai",
        "//third-party:reqwest",
        "//third-party:serde",
        "//third-party:serde_json",
        "//third-party:tokio",
    ]
)
